---
- name: Install NTP server
  apt:
          name: ntp
          state: latest
          update_cache: yes
- name: Validate NTP service state
  service:
          name: ntp
          state: started
          enabled: yes
