---
- name: Create container
  proxmox:
          node: {{ pve_node }}
          api_user: {{ pve_api_user }}
          api_password: {{ pve_api_password }}
          api_host: {{ pve_api_node }}
          password: firecore
          hostname: {{ inventory_hostname }}
          onboot: {{ vm_onboot }}
          ostemplate: 'firecore-img:/debian-10-standard_10.5-1_amd64.tar.gz'
          netif: '{"net0":"name=eth0,ip={{ vm_up_ip }},bridge={{ vm_up_network }}","net1":"net=eth1,ip={{ vm_management_ip }},bridge=management"}'
          cores: {{ vm_cores }}
          memory: {{ vm_ram }}
          disk: {{ vm_disk }}
          storage: firecore-fs
          nameserver: 10.1.0.10
          pubkey: {{ vm_publickey }}
          searchdomain: firecore.lab
          swap: 512
          timeout: 120
          unprivileged: yes
          state: started
  delegate_to: 127.0.0.1
- name: Wait for AllowRoot SSH manual configuration
  pause:
          prompt: "Connect to the container {{ inventory_hostname }} and verify that AllowRootLogin is set to 'prohibit-password'."
