---
- name: Install prerequisites
  delegate_to: 127.0.0.1
  pip:
          name:
                  - proxmoxer
                  - requests
          state: latest
  run_once: true
- name: Create container
  proxmox:
          node: "{{ pve_node }}"
          api_user: "{{ pve_api_user }}"
          api_password: "{{ pve_api_password }}"
          api_host: "{{ pve_api_node }}"
          password: "{{ pve_default_container_password }}"
          hostname: "{{ inventory_hostname }}"
          onboot: "{{ vm_onboot }}"
          ostemplate: "{{ vm_os_template }}"
          netif: '{"net0":"name=eth0,ip={{ vm_up_ip }},bridge={{ vm_up_network }}"}'
          cores: "{{ vm_cores }}"
          memory: "{{ vm_ram }}"
          disk: "{{ vm_disk }}"
          storage: firecore-fs
          nameserver: "{{ vm_up_dns }}"
          pubkey: "{{ vm_publickey }}"
          searchdomain: firecore.lab
          swap: 256
          timeout: 120
          unprivileged: "{{ vm_unprivileged }}"
          state: present
  delegate_to: 127.0.0.1
  throttle: 1
- name: Start the container
  proxmox:
          api_user: "{{ pve_api_user }}"
          api_password: "{{ pve_api_password }}"
          api_host: "{{ pve_api_node }}"
          hostname: "{{ inventory_hostname }}"
          state: started
  delegate_to: 127.0.0.1
  notify: Wait for container to enter ready state
- name: Flush notifications
  meta: flush_handlers
- name: Ping container
  ping:
  rescue:
          - name: RESCUE Restarting container
            proxmox:
                    api_user: "{{ pve_api_user }}"
                    api_password: "{{ pve_api_password }}"
                    api_host: "{{ pve_api_node }}"
                    hostname: "{{ inventory_hostname }}"
                    state: restarted
          - name: Wait for container reboot
            pause:
                    seconds: 10
- name: Gather facts
  setup:
