---
- name: Install prerequisites
  delegate_to: 127.0.0.1
  pip:
          name:
                  - proxmoxer
                  - requests
          state: latest
  run_once: true
- name: Create container
  proxmox:
          node: "pxvh{{ ['1', '2', '3'] | random }}"
          api_user: "{{ pve_api_user }}"
          api_password: "{{ pve_api_password }}"
          api_host: "{{ pve_api_node }}"
          password: "{{ pve_default_container_password }}"
          hostname: "{{ inventory_hostname }}"
          onboot: "{{ vm_onboot }}"
          ostemplate: 'firecore-img:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz'
          netif: '{"net0":"name=eth0,ip={{ vm_up_ip }},bridge={{ vm_up_network }},gw={{ vm_up_gateway }}"}'
          cores: "{{ vm_cores }}"
          memory: "{{ vm_ram }}"
          disk: "{{ vm_disk }}"
          storage: firecore-fs
          nameserver: 10.1.0.10
          pubkey: "{{ vm_publickey }}"
          searchdomain: firecore.lab
          swap: 256
          timeout: 120
          unprivileged: yes
          state: present
  delegate_to: 127.0.0.1
- name: Start the container
  proxmox:
          api_user: "{{ pve_api_user }}"
          api_password: "{{ pve_api_password }}"
          api_host: "{{ pve_api_node }}"
          hostname: "{{ inventory_hostname }}"
          state: started
  delegate_to: 127.0.0.1
  notify:
          - Wait for container boot
- name: Ping container
  ping:
