---
- name: Remove default site configuration
  file:
      path: /etc/nginx/sites-available/default
      state: absent
- name: Import configuration file
  notify: Restart Nginx
  template:
          src: "firecor-me.j2"
          dest: /etc/nginx/sites-available/firecor.me
