---
- name: Install prerequisites
  apt:
          update_cache: yes
          name:
                  - mariadb-client
                  - apache2-utils
                  - libapache2-mod-php
                  - php7.3
                  - php7.3-common
                  - php7.3-gd
                  - php7.3-mysql
                  - php7.3-imap
                  - php7.3-cli
                  - php7.3-cgi
                  - libapache2-mod-fcgid
                  - apache2-suexec-pristine
                  - php-pear
                  - mcrypt
                  - imagemagick
                  - libruby
                  - libapache2-mod-python
                  - php7.3-curl
                  - php7.3-intl
                  - php7.3-pspell
                  - php7.3-recode
                  - php7.3-sqlite3
                  - php7.3-tidy
                  - php7.3-xmlrpc
                  - php7.3-xsl
                  - memcached
                  - php-memcache
                  - php-imagick
                  - php-gettext
                  - php7.3-zip
                  - php7.3-mbstring
                  - libapache2-mod-passenger
                  - php7.3-soap
                  - php7.3-fpm
                  - php7.3-opcache
                  - php-apcu
                  - libapache2-reload-perl
- name: Enable Apache2 modules
  apache2_module:
          state: present
          name: "{{ item }}"
  loop:
          - suexec
          - rewrite
          - ssl
          - actions
          - include
          - cgi
          - headers
          - actions
          - proxy_fcgi
          - alias
- name: Unpack latest stable release
  unarchive:
          src: http://www.ispconfig.org/downloads/ISPConfig-3-stable.tar.gz
          remote_src: yes
          dest: /tmp
          creates: /tmp/ispconfig3_install
- name: Run installer
  pause:
          prompt: Connect to the machine and run php -q install.php to complete the installation. For virtual setups, choose expert mode.
