---
- name: Install Apache
  apt:
          name: apache2
          state: latest
          update_cache: yes
- name: Enable and start Apache service
  service:
          name: apache2
          state: started
          enabled: yes
