---
- name: Install apt-cacher-ng
  apt:
          name: apt-cacher-ng
          state: latest
          update_cache: yes
- name: Upload APT-Cacher-Ng configuration
  copy:
          src: acng.conf
          dest: /etc/apt-cacher-ng/acng.conf
  notify: Restart apt-cacher-ng
