---
- name: Install apt-cacher-ng
  apt:
          name: apt-cacher-ng
          state: latest
          update_cache: yes
- name: Upload APT-Cacher-Ng configuration
  pause:
          prompt: No configuration file present. Please update manually.
  notify: Restart apt-cacher-ng
