---
- name: Wait for container to enter ready state
  pause:
          seconds: 10
- name: Update apt cache
  apt:
          update_cache: yes
- name: Restart Filebeat
  service:
          name: filebeat
          state: restarted
- name: Restart ntpdate
  service:
          name: ntpdate
          state: restarted
- name: Restart Fail2Ban
  service:
    name: fail2ban
    state: restarted
- name: Restart Zabbix agent
  service:
          name: zabbix-agent
          state: restarted
