---
- name: Wait for container to enter ready state
  pause:
          seconds: 10
- name: Update apt cache
  apt:
          update_cache: yes
- name: Restart Filebeat
  service:
          name: filebeat
          state: restarted
- name: Restart ntpdate
  service:
          name: ntpdate
          state: restarted
