---
- name: Install prerequisites
  apt:
          name:
                  - apache2-dev
                  - bison
                  - build-essential
                  - ca-certificates
                  - curl
                  - dh-autoreconf
                  - doxygen
