galaxy_info:
  author: Joshua Zenn
  description: Elasticsearch with drop-in cluster configuration.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags: []
dependencies:
  - role: container-base
    vars:
      - vm_ram: 2048
      - vm_disk: 16 
