galaxy_info:
  author: Joshua Zenn
  description: Base initialization for Vyos L3 and L2 routers.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Vyos
      versions:
        - 1.3
  galaxy_tags: []
dependencies: []
  
