galaxy_info:
  author: Joshua Zenn
  description: Deploys an instance of Vigil status page with host HTTP service monitoring.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags: []
dependencies:
        - container-base
