---
- name: Restart Zabbix
  service:
          name:
                  - zabbix-server
                  - zabbix-agent
                  - nginx
                  - php7.3-fpm
          state: restarted
