---
- name: Install requirements
  apt:
    name:
      - curl
      - gcc
    state: latest
    update_cache: yes
- name: Copy configuration file
  template:
    src: "config.cfg.j2"
    dest: /opt/config.cfg
  notify: Restart Vigil