---
- name: Install requirements
  apt:
    name: curl
    state: latest
    updat_cache: yes
- name: Run installer
  shell: "curl https://sh.rustup.rs -sSf | sh"
- name: Install vigil
  shell: cargo install vigil-server
