galaxy_info:
  author: Joshua Zenn
  description: Dynamic DNS to update domain registration info with dynamic IP.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags: []
dependencies:
  - role: container-base
    vars:
      - vm_ram: 128
      - vm_disk: 3
