galaxy_info:
  author: Joshua Zenn
  description: GNS VM for use with a GNS3 environment.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags: []
dependencies:
  - role: container-base
    vars:
      - vm_os_template: "firecore-img:vztmpl/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz"
      - vm_cores: 2
      - vm_ram: 4096
      - vm_disk: 80 
      - vm_unprivileged: no
