galaxy_info:
  author: Joshua Zenn
  description: Role for an APT cache for Debian and Ubuntu systems on the network.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags: []
dependencies:
  - role: container-base
    vars:
      vm_disk: 25 
