---
- name: Install prerequisites
  apt:
          name:
                  - openjdk-11-jre
                  - unzip
                  - tar
          state: latest
          update_cache: yes
- name: Create directories
  file:
          path: /opt/spark
          state: directory
          mode: '0777'
- name: Download Apache Spark
  unarchive:
          src: https://apache.osuosl.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz 
          dest: /opt/spark
          remote_src: yes
          creates: /opt/spark
