galaxy_info:
  author: Joshua Zenn
  description: Reverse proxy using Nginx.
  company: Firecore Lab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags: []
dependencies:
  - nginx
  
